### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by macor161** [macor161/quantal#74]
# Quantal Roadmap

## 1. Cache Implementation, CI and Code Refactor
- [x] Cache implementation
- [ ] Code refactoring
- [x] Add missing solc binary versions
- [x] Set up linter and continuous integration
- [ ] Add checksum validation for downloaded solc binaries
- [x] Improve test coverage
- [ ] Beta release

## 2. Production Release
- Windows support
- Fix AST IDs collisions
- Improve dependency tree algorithm
- Feature freeze
- Fix remaining bugs
- Complete unit and integration tests
- Audit
- v1.0 release

## 3. Post-Release Work
- Quantal JS library  
- Improve compile speed
- Experimental ewasm support
- Web3.js, ethers.js contract objects generation
